"""Agent State Definition for LangGraph"""
from typing import TypedDict, List, Annotated, Literal
from langgraph.graph import add_messages

class AgentState(TypedDict):
    """State for the autonomous coding agent (Pod Architecture)"""
    messages: Annotated[List, add_messages]
    
    # Input/Context
    task: str
    context: str
    project_root: str
    
    # Agent Artifacts
    strategy: str   # Generated by Architect
    commands: List[str] # Generated by Coder
    
    # Workflow Control
    current_step: str
    review_status: Literal["approved", "rejected", "pending"]
    review_feedback: str
